# DevBuddy config file
# See https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md

env:
  ENV: development

up:
  - go:
      version: 1.25.1
      modules: true

commands:
  test:
    desc: Run tests
    run: go test -timeout=5s -cover ./...
  lint:
    desc: Lint the project
    run: golangci-lint run

open:
  devbuddy: https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md#config-devyml